<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Madar.Api</RootNamespace>
    <AssemblyName>Madar.Api</AssemblyName>
    <IsPackable>false</IsPackable>
    <UserSecretsId>Madar-Local-Development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Madar.Domain\Madar.Domain.csproj" />
    <ProjectReference Include="..\Madar.Application\Madar.Application.csproj" />
    <ProjectReference Include="..\Madar.Infrastructure\Madar.Infrastructure.csproj" />
    <ProjectReference Include="..\Madar.Contracts\Madar.Contracts.csproj" />
    <ProjectReference Include="..\Madar.Client\Madar.Client.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Application\FoundationKit.Application.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Infrastructure\FoundationKit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.WebApi\FoundationKit.WebApi.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Security\FoundationKit.Security.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Identity\FoundationKit.Identity.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Authorization\FoundationKit.Authorization.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Auditing\FoundationKit.Auditing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
