import { codeBlock } from '../components/code-block.js';
import { simpleTable } from '../components/data-table.js';
import { escapeHtml, route } from '../components/dom-utils.js';
export function renderHomePage(root, repository) {
  const doc = repository.getDocumentControl(); const apis = repository.getApis(); const matrix = repository.getSuccessMatrix(); const names = repository.getContractNamingNotice();
  return `<section class="hero page-enter"><div class="hero-grid"><div><div class="page-kicker">Enterprise Developer Portal</div><h1>ENTERTAINMENT<br>SERVICES API</h1><div class="hero-subtitle">Integration and Purchase Processing Guide</div><p>A modular, domain-oriented documentation experience for authentication, catalog discovery, purchase initialization, one-time execution, and final state verification.</p><div class="page-actions"><a class="btn btn-primary" href="${route(root,'pages/quick-start.html')}">Start Integration</a><a class="btn btn-soft" href="${route(root,'pages/api-reference.html')}">Explore APIs</a><a class="btn" href="${route(root,'pages/purchase-flow.html')}">View Purchase Flow</a></div></div><div class="hero-meta"><div class="meta-row"><span>Document Reference</span><strong>${doc.reference}</strong></div><div class="meta-row"><span>Version</span><strong>${doc.version}</strong></div><div class="meta-row"><span>Environment</span><strong>${doc.environment}</strong></div><div class="meta-row"><span>Status</span><strong>${doc.status}</strong></div><div class="meta-row"><span>Classification</span><strong>${doc.classification}</strong></div></div></div></section>
  <section class="section page-enter"><div class="page-kicker">At a glance</div><h2 class="section-title">Overview Dashboard</h2><p class="section-lead">A compact view of the integration surface, validated journey, and document controls.</p><div class="grid-4">${[['Total APIs',String(apis.length),'Authentication, catalog, and purchase'],['Authentication','Bearer Token','Login is public'],['Method Pattern','POST','Current documented operations'],['Validated Flow','1','PUBG 120 purchase journey'],['Tested APIs','5','All documented endpoints'],['Main Identifiers','3','resolutionID, requestId, referenceID'],['Version',doc.version,'Initial controlled issue'],['Environment',doc.environment,'No production secrets included']].map(([label,value,note])=>`<article class="card metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></article>`).join('')}</div></section>
  <section class="section page-enter"><div class="callout callout-danger"><div>⚠️</div><div><h3>Critical execution rule</h3><p>Execute Purchase must not be repeated when the response is delayed, interrupted, or uncertain. Call Check Purchase State using the same <code>requestId</code>.</p></div></div></section>
  <section class="section page-enter"><div class="page-kicker">Integration surface</div><h2 class="section-title">API Portfolio</h2><p class="section-lead">Each API has a controlled reference, purpose, request contract, response contract, rules, and retry guidance.</p><div class="grid-3">${apis.map((api)=>`<article class="card api-card"><div class="api-ref">${api.ref}</div><h3>${escapeHtml(api.name)}</h3><p>${escapeHtml(api.purpose)}</p><div class="api-card-footer"><span class="badge badge-method">${api.method}</span><span class="badge badge-success">${api.status}</span><a href="${route(root,`pages/api-reference.html#${api.ref.toLowerCase()}`)}">Open</a></div></article>`).join('')}</div></section>
  <section class="section page-enter"><div class="page-kicker">Architecture</div><h2 class="section-title">Clean Architecture, DDD-aligned Frontend</h2><p class="section-lead">The site is intentionally organized around business concepts and use cases rather than page scripts.</p><div class="architecture-map"><article class="card layer-card"><h3>Domain</h3><p>API contracts, purchase flow, identifiers, quality evidence, limitations, and governance concepts.</p></article><article class="card layer-card"><h3>Application</h3><p>Search, request construction, validation, error decisioning, and test filtering use cases.</p></article><article class="card layer-card"><h3>Infrastructure</h3><p>Static documentation repository, browser preferences, and service-worker caching adapters.</p></article><article class="card layer-card"><h3>Presentation</h3><p>Reusable shell, navigation, command palette, code blocks, tables, and page renderers.</p></article></div></section>
  <section class="section page-enter"><div class="grid-2"><div>${codeBlock(repository.getResponseEnvelope(),'Common response envelope')}</div><div class="panel"><h3>Success validation matrix</h3>${simpleTable(['Validation level','Successful value'],matrix.map(([a,b])=>[escapeHtml(a),`<code>${escapeHtml(b)}</code>`]))}<p class="muted"><strong>HTTP 200 alone does not confirm that the business transaction succeeded.</strong></p></div></div></section>
  <section class="section page-enter"><div class="callout"><div>ℹ️</div><div><h3>Current contract naming</h3><p>The current contract includes ${names.map((name)=>`<code>${name}</code>`).join(', ')}. Clients must use these names exactly as implemented in the current API version.</p></div></div></section>`;
}
