import { buildPurchaseRequests, validatePurchaseInputs } from '../../application/use-cases/build-purchase-requests.js';
import { codeBlock } from '../components/code-block.js';
import { escapeHtml } from '../components/dom-utils.js';
const defaults={serviceCode:'pubg',offerCode:'120',fieldID:'1',value:'PLAYER_ID_SAMPLE',requestId:'REQ-SAMPLE-0001',resolutionID:'SAMPLE-RESOLUTION-ID'};
export function renderPlaygroundPage(){return `<header class="page-header page-enter"><div class="page-kicker">Safe educational simulation</div><h1 class="page-title">Offline API Playground</h1><p class="page-lead">Build the three purchase requests locally. No request is sent, no credentials are stored, and no live endpoint is contacted.</p></header><section class="callout page-enter"><div>🔒</div><div><h3>Offline Simulation — No API request will be sent.</h3><p>All values remain in the current browser session.</p></div></section><section class="section grid-2 page-enter"><div class="panel"><div class="field"><label for="playMode">Example mode</label><select id="playMode"><option value="pubg">PUBG 120 Example</option><option value="custom">Custom Example</option></select></div><div class="form-grid" style="margin-top:14px">${Object.entries(defaults).map(([key,value])=>`<div class="field"><label for="pg-${key}">${key}</label><input id="pg-${key}" data-pg-field="${key}" value="${escapeHtml(value)}" autocomplete="off"></div>`).join('')}</div><div class="page-actions"><button class="btn btn-primary" id="resetPlayground">Reset</button><button class="btn" id="clearPlayground">Clear</button></div><p id="playgroundValidation" class="muted" role="status"></p></div><div class="tabs" data-tabs id="playgroundTabs"><div class="tab-list"><button class="tab-btn" data-tab="initial" aria-selected="true">Initial Purchase</button><button class="tab-btn" data-tab="execute" aria-selected="false">Execute Purchase</button><button class="tab-btn" data-tab="check" aria-selected="false">Check Purchase State</button></div><div class="tab-panel" data-panel="initial"><div id="playgroundPreview"></div></div><div class="tab-panel" data-panel="execute" hidden></div><div class="tab-panel" data-panel="check" hidden></div></div></section>`;}
export function initPlaygroundPage(){
  const fields=[...document.querySelectorAll('[data-pg-field]')];let mode='initial';
  const values=()=>Object.fromEntries(fields.map((input)=>[input.dataset.pgField,input.value]));
  const render=()=>{const all=buildPurchaseRequests(values());const validation=validatePurchaseInputs(values(),mode);document.querySelectorAll('#playgroundTabs [data-panel]').forEach((panel)=>{if(panel.dataset.panel===mode)panel.innerHTML=`<div id="playgroundPreview">${codeBlock(all[mode],`${mode} request`)}</div>`;});const status=document.getElementById('playgroundValidation');status.textContent=validation.valid?'Valid JSON preview.':`Missing: ${validation.missing.join(', ')}`;status.style.color=validation.valid?'var(--success)':'var(--danger)';};
  document.getElementById('playgroundTabs').addEventListener('click',(event)=>{const tab=event.target.closest('[data-tab]');if(tab){mode=tab.dataset.tab;setTimeout(render,0);}});
  fields.forEach((field)=>field.addEventListener('input',render));
  document.getElementById('resetPlayground').addEventListener('click',()=>{fields.forEach((input)=>input.value=defaults[input.dataset.pgField]);document.getElementById('playMode').value='pubg';render();});
  document.getElementById('clearPlayground').addEventListener('click',()=>{fields.forEach((input)=>input.value='');document.getElementById('playMode').value='custom';render();});
  document.getElementById('playMode').addEventListener('change',(event)=>{if(event.target.value==='pubg')fields.forEach((input)=>input.value=defaults[input.dataset.pgField]);else fields.forEach((input)=>input.value='');render();});render();
}
