<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\examples\Athar\Athar.Api\Athar.Api.csproj" />
    <ProjectReference Include="..\..\examples\Athar\Athar.Domain\Athar.Domain.csproj" />
    <ProjectReference Include="..\..\examples\Athar\Athar.Contracts\Athar.Contracts.csproj" />
    <ProjectReference Include="..\..\src\FoundationKit.Security\FoundationKit.Security.csproj" />
  </ItemGroup>
</Project>
