<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>FoundationKit.CatalogGenerator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FoundationKit.Application\FoundationKit.Application.csproj" />
  </ItemGroup>
</Project>
