<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Athar.Api</RootNamespace>
    <AssemblyName>Athar.Api</AssemblyName>
    <IsPackable>false</IsPackable>
    <UserSecretsId>Athar-Production-Reference-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Athar.Domain\Athar.Domain.csproj" />
    <ProjectReference Include="..\Athar.Application\Athar.Application.csproj" />
    <ProjectReference Include="..\Athar.Infrastructure\Athar.Infrastructure.csproj" />
    <ProjectReference Include="..\Athar.Contracts\Athar.Contracts.csproj" />
    <ProjectReference Include="..\Athar.Client\Athar.Client.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Domain\FoundationKit.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Application\FoundationKit.Application.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.Infrastructure\FoundationKit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\FoundationKit.WebApi\FoundationKit.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
