<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>EntertainmentDocs.Infrastructure</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntertainmentDocs.Domain\EntertainmentDocs.Domain.csproj" />
    <ProjectReference Include="..\EntertainmentDocs.Application\EntertainmentDocs.Application.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>
