<Project>
  <Import Project="..\Directory.Build.props" />
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageVersion>0.1.0</PackageVersion>
    <Authors>ALHassan ALShami</Authors>
    <RepositoryUrl>https://github.com/a2sn2/foundationkit-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://a2sn2.github.io/entertainment-api-docs/</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>clean-architecture;ddd;dotnet;foundation;building-blocks</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
