<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageVersion>0.1.0</PackageVersion>
    <Authors>ALHassan ALShami</Authors>
    <Company>FoundationKit</Company>
    <RepositoryUrl>https://github.com/a2sn2/foundationkit-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/a2sn2/foundationkit-dotnet</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>clean-architecture;ddd;dotnet;foundation;building-blocks</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md"
          Pack="true"
          PackagePath="\" />
  </ItemGroup>
</Project>
