<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <RootNamespace>EntertainmentDocs.Admin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntertainmentDocs.Ui\EntertainmentDocs.Ui.csproj" />
    <ProjectReference Include="..\..\src\EntertainmentDocs.Contracts\EntertainmentDocs.Contracts.csproj" />
    <ProjectReference Include="..\..\core\FoundationKit.Blazor\FoundationKit.Blazor.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>
</Project>
